### ISSUE TITLE
Bug Report: failed Tests in StorageServiceTest

### ISSUE THREAD

**Issue by Nevram26** [Aizakkuuu/TaskManager#4]
**Summary**
Four the tests in the class StorageServiceTest failed, impacting task loading and the saving functionality.

**Failed Tests**
1. loadTasks should handle exceptions gracefully
2. loadTasks should return empty list when file does not exist
3. same Task ID should not save
4. saveTasks should save tasks to file

**Expected Behavior**
All tests in this class should pass, having proper handling of task storage.

**Actual Behavior**
Test fail due to errors in exception handling, file handling, and duplicate ID detection

**Comment by Aizakkuuu** [comment]
I've created a fix in branch dev/bugfix/fix-storage-service-bugs.

Changes were made to:
StorageService.kt:
-The StorageService constructor now accepts a base directory. (For more flexible file storage).
- saveTasks() method now prevents multiple IDs

The tests in StorageServiceTest also had some issues:
- Hardcoded file path assumptions
- Not using a consistent temporary location for test files
- Potential conflicts with file locations during testing

Do update me if there the fix is sufficient and if there are any more issues.
